# Generated by Django 4.0.1 on 2022-02-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('100', 'FIRST YEAR'), ('200', 'SECOND YEAR'), ('300', 'THIRD YEAR'), ('400', 'FOURTH YEAR')], default='100', max_length=3)),
                ('slug_name', models.SlugField(max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
